# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alpine Lodge 211 Free and Accepted Masons
email: 
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the home of Alpine Lodge. Founded in 1890, Alpine Lodge has been practicing Freemasonry in the Menlo, Georgia community for over 125 years. Here, you'll find news and other information about the Lodge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alpinelodge211fam.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
